# -*- coding: utf-8 -*-
"""quizz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jKSJ-Q127eqDHTwhbqjBxN8UWKF3VVw3
"""

def qu1():
  q1=print("which of the following malware replaces?\n (a)trojon \n(b)virus \n(c)worm \n\n")
  a1="b"
  a=input("answer:")
  s1=0
  if(a.lower()== a1):
    print("correct!\n")
    s1=s1+1
  else:
    print("wrong ans!\n")
  return(s1)
def qu2():
  q1=print("which of the following malware replaces?\n (a)trojon \n(b)virus \n(c)worm \n\n")
  a1="b"
  a=input("answer:")
  s2=0
  if(a.lower()== a1):
    print("correct!\n")
    s2=s2+1
  else:
    print("wrong ans!\n")
  return(s2)
def qu3():
  q1=print("which of the following malware replaces?\n (a)trojon \n(b)virus \n(c)worm \n\n")
  a1="b"
  a=input("answer:")
  s3=0
  if(a.lower()== a1):
    print("correct!\n")
    s3=s3+1
  else:
    print("wrong ans!\n")
  return(s3)
def qu4():
  q1=print("which of the following malware replaces?\n (a)trojon \n(b)virus \n(c)worm \n\n")
  a1="b"
  a=input("answer:")
  s4=0
  if(a.lower()== a1):
    print("correct!\n")
    s4=s4+1
  else:
    print("wrong ans!\n")
  return(s4)
def qu5():
  q1=print("which of the following malware replaces?\n (a)trojon \n(b)virus \n(c)worm \n\n")
  a1="b"
  a=input("answer:")
  s5=0
  if(a.lower()== a1):
    print("correct!\n")
    s5=s5+1
  else:
    print("wrong ans!\n")
  return(s5)
s1=qu1()
s2=qu2()
s3=qu3()
s4=qu4()
s5=qu5()
print(s1+s2+s3+s4+s5)