# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mrGcXJbkoLQmHhamfnVQu2oSpMrOSWIw
"""

year=int(input("Enter the year b/w 1980 to 2010 for albums :"))
if(year>=1980):
	print("The Given",year,"is 80s albums")
elif(year>1989 or year==1999):
	print("The Given",year,"is 90s albums")
elif(year>1999 or year==2010):
	print("The Given",year,"is 20s albums")
else:
	print("You Enter year is Invalid")

print("Find Leap Year b/w Two Given Year")
y1=int(input("Enter Starting Year:"))
y2=int(input("Enter Ending Year:"))
if y1<=y2:
  print("Here is the list of leap year b/w",y1,"and",y2,":")
  while y1 <= y2:
    if (y1%4==0 and y1%100!=0):
      print(y1)
    elif(y1%100==0 and y1%400==0):
      print(y1)
    y1+=1

for a in range(101):
    if a % 3 == 0 and a % 5 == 0:
        print("fizzbuzz")
        continue
    elif a % 3 == 0:
        print("fizz")
        continue
    elif a % 5 == 0:
        print("buzz")
        continue
    print(a)

for fizzbuzz in range(51):
    if fizzbuzz % 3 == 0 and fizzbuzz % 5 == 0:
        print("fizzbuzz")
        continue
    elif fizzbuzz % 3 == 0:
        print("fizz")
        continue
    elif fizzbuzz % 5 == 0:
        print("buzz")
        continue
    print(fizzbuzz)